# Generated by Django 4.2.7 on 2025-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='detalle_carrito',
            field=models.TextField(blank=True, help_text='JSON con los productos del carrito'),
        ),
    ]
