# Generated by Django 4.2.7 on 2025-06-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_transaccion_detalle_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente de Revisión'), ('ACEPTADO', 'Aceptado por Vendedor'), ('RECHAZADO', 'Rechazado por Vendedor'), ('EN_PREPARACION', 'En Preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE_REVISION', max_length=20),
        ),
    ]
